In [2]:
!pip install gdown -U
!pip install evaluate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.5 MB/s eta 0:00:00


In [3]:
import os
os.environ["WANDB_DISABLED"]="true"

In [4]:
!mkdir -p results_docs_bert

In [5]:
# cargar dataset de google drive
!gdown '1pl9hGX3_4lMJvl4thbwkEXRCTi_dH1au'

Downloading...
From: https://drive.google.com/uc?id=1pl9hGX3_4lMJvl4thbwkEXRCTi_dH1au
To: /kaggle/working/ReWoRC_Dataset_req.csv
100%|█████████████████████████████████████████| 437k/437k [00:00<00:00, 104MB/s]


Aqui empiezo el código igual al de colab

In [6]:
from datasets import load_dataset

In [7]:
FILE_REQ='/kaggle/working/ReWoRC_Dataset_req.csv'
data_req = load_dataset('csv', data_files=FILE_REQ, sep=';')
print(data_req['train']['NFR'][21])

def create_labels(row):
  return {'labels': 'F' if row['NFR'] == 'Funcional' else 'NF', 'id_doc':row['Documento']}

data_req = data_req.map(create_labels)
data_req = data_req.class_encode_column('labels')
data_req = data_req.class_encode_column('id_doc')
print(set(data_req['train']['labels']))
data_req = data_req['train']
data_req.features

Generating train split: 0 examples [00:00, ? examples/s]

No funcional


Map:   0%|          | 0/2391 [00:00<?, ? examples/s]

Casting to class labels:   0%|          | 0/2391 [00:00<?, ? examples/s]

Casting to class labels:   0%|          | 0/2391 [00:00<?, ? examples/s]

{0, 1}


{'Num': Value(dtype='int64', id=None),
 'Referencia': Value(dtype='string', id=None),
 'Requisito': Value(dtype='string', id=None),
 'Documento': Value(dtype='string', id=None),
 'NFR': Value(dtype='string', id=None),
 'labels': ClassLabel(names=['F', 'NF'], id=None),
 'id_doc': ClassLabel(names=['0000 - gamma j.pdf', '0000 - inventory.pdf', '1998 - themas.pdf', '1999 - multi-mahjong.html', '2001 - beyond.pdf', '2001 - ctc network.pdf', '2001 - esa.pdf', '2001 - hats.pdf', '2001 - libra.doc', '2001 - space fractions.pdf', '2002 - evla back.pdf', '2002 - evla corr.pdf', '2003 - agentmom.pdf', '2003 - pnnl.pdf', '2003 - qheadache.pdf', '2003 - tachonet.pdf', '2004 - colorcast.pdf', '2004 - ijis.doc', '2004 - phillips.doc', '2004 - rlcs.pdf', '2004 - sprat.pdf', '2005 - clarus low.pdf', '2005 - grid 3D.pdf', '2005 - microcare.pdf', '2005 - nenios.html', '2005 - phin.pdf', '2005 - pontis.pdf', '2005 - triangle.pdf', '2005 - znix.pdf', '2006 - stewards.pdf', '2007 - e-store.pdf', '2007 - ei

In [22]:
from transformers import AutoTokenizer
#BERT: model_name = 'google-bert/bert-base-cased'
#DEBERTA: model_name = 'microsoft/deberta-v3-base'
#ROBERTA: model_name = 'FacebookAI/roberta-base'
model_name = 'google-bert/bert-base-cased' # modificar con el modelo que queramos cada vez

In [23]:
tokenizer = AutoTokenizer.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/579 [00:00<?, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

/opt/conda/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py:562: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(


In [24]:
def encode_text(row, tokenizer):
  row_encode = tokenizer(row['Requisito'], truncation=True)
  return row_encode


encode_data = data_req.map(encode_text, fn_kwargs={'tokenizer':tokenizer})
encode_data

from sklearn.model_selection import KFold
import numpy as np

folds = KFold(n_splits=10, shuffle=True)

splits = folds.split(np.zeros(50))
test_sets = []
train_val_sets = []
i=1
for train_val_idxs, test_idxs in splits:
  print (i)
  print(test_idxs)
  print('*******')
  data_test = encode_data.filter(lambda r : r['id_doc'] in test_idxs)
  data_train = encode_data.filter(lambda r : r['id_doc'] in train_val_idxs)
  data_train_val = data_train.train_test_split(train_size=0.9, stratify_by_column='labels')
  print(data_test)
  print(data_train)
  print(data_test.num_rows + data_train.num_rows)
  print(encode_data.num_rows == (data_test.num_rows + data_train.num_rows))
  print("***")


  test_sets.append(data_test)
  train_val_sets.append(data_train_val)
  i = i + 1

print(test_sets[0])
print(train_val_sets[0]['test'])

Map:   0%|          | 0/2391 [00:00<?, ? examples/s]

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


1
[13 17 30 39 45]
*******


Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 249
})
Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 2142
})
2391
True
***
2
[19 25 26 32 48]
*******


Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 446
})
Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 1945
})
2391
True
***
3
[ 3  4  8 12 37]
*******


Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 196
})
Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 2195
})
2391
True
***
4
[ 6 15 41 46 47]
*******


Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 183
})
Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 2208
})
2391
True
***
5
[ 9 16 24 31 34]
*******


Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 244
})
Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 2147
})
2391
True
***
6
[ 0  5 27 33 44]
*******


Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 189
})
Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 2202
})
2391
True
***
7
[ 1 11 21 29 36]
*******


Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 244
})
Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 2147
})
2391
True
***
8
[ 2 23 35 40 43]
*******


Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 169
})
Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 2222
})
2391
True
***
9
[10 18 20 22 49]
*******


Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 183
})
Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 2208
})
2391
True
***
10
[ 7 14 28 38 42]
*******


Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2391 [00:00<?, ? examples/s]

Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 288
})
Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 2103
})
2391
True
***
Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 249
})
Dataset({
    features: ['Num', 'Referencia', 'Requisito', 'Documento', 'NFR', 'labels', 'id_doc', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 215
})


In [25]:
from transformers import AutoModelForSequenceClassification
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

pytorch_model.bin:   0%|          | 0.00/371M [00:00<?, ?B/s]

/opt/conda/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [26]:
import evaluate
import numpy as np

In [27]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis = 1)
    return metric.compute(predictions=predictions, references=labels)

# load metric
metric_name = 'f1'
metric = evaluate.load(metric_name)

In [28]:
import glob
from transformers import TrainingArguments, Trainer
from sklearn.metrics import classification_report

lr_values =[2e-5, 5e-5]

for j in range(len(train_val_sets)):
    best_lr = -1
    best_f1 = -1

    # para escribir los resultados
    with open(f'results_docs_bert/res_docs_bert_{j}.txt', 'w') as f:
    # NOTA: si no va, deshacer el tab extra del siguiente bucle for
      for i, lr in enumerate(lr_values):
        print("================================================")
        print("j = " + str(j) + " // lr = " + str(lr))
        print("================================================")
      # argumentos para el entrenamiento
        training_args = TrainingArguments(
            #output_dir="my_checkpoint"+str(j),
            output_dir=f"my_checkpoint_{i}",
            overwrite_output_dir = True,
            num_train_epochs=10,
            #para probar tanto promise como nuestro coger 10 epochs
            evaluation_strategy="epoch",
            save_strategy="epoch",
            save_total_limit = 1,
            load_best_model_at_end=True,
            logging_strategy='epoch',
            optim="adamw_torch",
            per_device_train_batch_size=32,
            #lo dejaremos en 32
            #per_device_eval_batch_size=32,
            learning_rate=lr,
            #probar tanto 2e-5 como 5e-5
            weight_decay=0.01,
        )

        model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)
        # declarar el "entrenador"
        trainer = Trainer(
            model=model,
            args=training_args,
            train_dataset=train_val_sets[j]['train'],
            eval_dataset=train_val_sets[j]['test'],
            tokenizer=tokenizer,
            compute_metrics=compute_metrics
        )

        # realizar el entrenamiento
        trainer.train()

        out_pred = trainer.predict(data_train_val['test'])
        if out_pred.metrics['test_f1'] > best_f1:
          best_f1 = out_pred.metrics['test_f1']
          best_lr = i
      # cargar el mejor modelo y resultados para test
      best_dir = glob.glob(f"my_checkpoint_{best_lr}/checkpoint*")
      print(best_dir)
      model_best = AutoModelForSequenceClassification.from_pretrained(best_dir[0])
      trainer_best = Trainer(
            model=model_best,
            args=None,
            train_dataset=None,
            eval_dataset=None,
            tokenizer=tokenizer,
            compute_metrics=compute_metrics
        )

      test_data = test_sets[j]
      outputs_pred = trainer_best.predict(test_dataset=test_data)

      # model predictions
      predictions = np.argmax(outputs_pred.predictions, axis=1)

      #d_res = classification_report(test_data['labels'], predictions, digits=3, return_dict = True)
      d_res = classification_report(test_data['labels'], predictions, digits=3, output_dict=True)
      print(d_res)
      f.write("================== Best lr ================\n")
      f.write(str(best_lr))
      f.write("\n")
      f.write( "================== Resultados ================\n")
      f.write(str(d_res))

/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


j = 0 // lr = 2e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


j = 0 // lr = 5e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


['my_checkpoint_1/checkpoint-183']


Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


{'0': {'precision': 0.875, 'recall': 0.9792746113989638, 'f1-score': 0.9242053789731052, 'support': 193}, '1': {'precision': 0.8787878787878788, 'recall': 0.5178571428571429, 'f1-score': 0.651685393258427, 'support': 56}, 'accuracy': 0.8755020080321285, 'macro avg': {'precision': 0.8768939393939394, 'recall': 0.7485658771280533, 'f1-score': 0.7879453861157661, 'support': 249}, 'weighted avg': {'precision': 0.8758518924181575, 'recall': 0.8755020080321285, 'f1-score': 0.8629157436316514, 'support': 249}}
j = 1 // lr = 2e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


j = 1 // lr = 5e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


['my_checkpoint_1/checkpoint-330']


Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


{'0': {'precision': 0.9794344473007712, 'recall': 0.9292682926829269, 'f1-score': 0.9536921151439298, 'support': 410}, '1': {'precision': 0.49122807017543857, 'recall': 0.7777777777777778, 'f1-score': 0.6021505376344085, 'support': 36}, 'accuracy': 0.9170403587443946, 'macro avg': {'precision': 0.7353312587381049, 'recall': 0.8535230352303523, 'f1-score': 0.7779213263891691, 'support': 446}, 'weighted avg': {'precision': 0.9400276545283229, 'recall': 0.9170403587443946, 'f1-score': 0.9253165618023541, 'support': 446}}
j = 2 // lr = 2e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


j = 2 // lr = 5e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


['my_checkpoint_1/checkpoint-124']


Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


{'0': {'precision': 0.9367088607594937, 'recall': 0.9548387096774194, 'f1-score': 0.9456869009584665, 'support': 155}, '1': {'precision': 0.8157894736842105, 'recall': 0.7560975609756098, 'f1-score': 0.7848101265822786, 'support': 41}, 'accuracy': 0.9132653061224489, 'macro avg': {'precision': 0.8762491672218521, 'recall': 0.8554681353265146, 'f1-score': 0.8652485137703725, 'support': 196}, 'weighted avg': {'precision': 0.9114144991774191, 'recall': 0.9132653061224489, 'f1-score': 0.9120341063185496, 'support': 196}}
j = 3 // lr = 2e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


j = 3 // lr = 5e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


['my_checkpoint_0/checkpoint-189']


Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


{'0': {'precision': 0.9, 'recall': 0.9, 'f1-score': 0.9, 'support': 150}, '1': {'precision': 0.5454545454545454, 'recall': 0.5454545454545454, 'f1-score': 0.5454545454545454, 'support': 33}, 'accuracy': 0.8360655737704918, 'macro avg': {'precision': 0.7227272727272727, 'recall': 0.7227272727272727, 'f1-score': 0.7227272727272727, 'support': 183}, 'weighted avg': {'precision': 0.8360655737704918, 'recall': 0.8360655737704918, 'f1-score': 0.8360655737704918, 'support': 183}}
j = 4 // lr = 2e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


j = 4 // lr = 5e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


['my_checkpoint_0/checkpoint-122']


Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


{'0': {'precision': 0.9861111111111112, 'recall': 0.9466666666666667, 'f1-score': 0.9659863945578231, 'support': 225}, '1': {'precision': 0.5714285714285714, 'recall': 0.8421052631578947, 'f1-score': 0.6808510638297872, 'support': 19}, 'accuracy': 0.9385245901639344, 'macro avg': {'precision': 0.7787698412698413, 'recall': 0.8943859649122807, 'f1-score': 0.8234187291938051, 'support': 244}, 'weighted avg': {'precision': 0.9538202576112412, 'recall': 0.9385245901639344, 'f1-score': 0.9437832335585087, 'support': 244}}
j = 5 // lr = 2e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


j = 5 // lr = 5e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


['my_checkpoint_0/checkpoint-186']


Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


{'0': {'precision': 0.9424460431654677, 'recall': 0.9290780141843972, 'f1-score': 0.9357142857142857, 'support': 141}, '1': {'precision': 0.8, 'recall': 0.8333333333333334, 'f1-score': 0.816326530612245, 'support': 48}, 'accuracy': 0.9047619047619048, 'macro avg': {'precision': 0.8712230215827339, 'recall': 0.8812056737588653, 'f1-score': 0.8760204081632654, 'support': 189}, 'weighted avg': {'precision': 0.9062692702980474, 'recall': 0.9047619047619048, 'f1-score': 0.905393586005831, 'support': 189}}
j = 6 // lr = 2e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


j = 6 // lr = 5e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


['my_checkpoint_0/checkpoint-183']


Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


{'0': {'precision': 0.8833333333333333, 'recall': 0.8983050847457628, 'f1-score': 0.8907563025210085, 'support': 177}, '1': {'precision': 0.71875, 'recall': 0.6865671641791045, 'f1-score': 0.7022900763358778, 'support': 67}, 'accuracy': 0.8401639344262295, 'macro avg': {'precision': 0.8010416666666667, 'recall': 0.7924361244624336, 'f1-score': 0.7965231894284431, 'support': 244}, 'weighted avg': {'precision': 0.838140368852459, 'recall': 0.8401639344262295, 'f1-score': 0.8390053305767307, 'support': 244}}
j = 7 // lr = 2e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


j = 7 // lr = 5e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


['my_checkpoint_0/checkpoint-189']


Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


{'0': {'precision': 0.9753086419753086, 'recall': 0.9813664596273292, 'f1-score': 0.978328173374613, 'support': 161}, '1': {'precision': 0.5714285714285714, 'recall': 0.5, 'f1-score': 0.5333333333333333, 'support': 8}, 'accuracy': 0.9585798816568047, 'macro avg': {'precision': 0.7733686067019401, 'recall': 0.7406832298136645, 'f1-score': 0.7558307533539732, 'support': 169}, 'weighted avg': {'precision': 0.9561900587541613, 'recall': 0.9585798816568047, 'f1-score': 0.9572633288756176, 'support': 169}}
j = 8 // lr = 2e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


j = 8 // lr = 5e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


['my_checkpoint_0/checkpoint-189']


Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


{'0': {'precision': 0.9875, 'recall': 0.9753086419753086, 'f1-score': 0.9813664596273292, 'support': 162}, '1': {'precision': 0.8260869565217391, 'recall': 0.9047619047619048, 'f1-score': 0.8636363636363636, 'support': 21}, 'accuracy': 0.9672131147540983, 'macro avg': {'precision': 0.9067934782608695, 'recall': 0.9400352733686067, 'f1-score': 0.9225014116318464, 'support': 183}, 'weighted avg': {'precision': 0.9689771917320029, 'recall': 0.9672131147540983, 'f1-score': 0.9678564486119723, 'support': 183}}
j = 9 // lr = 2e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


/opt/conda/lib/python3.10/site-packages/transformers/training_args.py:1494: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


j = 9 // lr = 5e-05


Some weights of DebertaV2ForSequenceClassification were not initialized from the model checkpoint at microsoft/deberta-v3-base and are newly initialized: ['classifier.bias', 'classifier.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


['my_checkpoint_1/checkpoint-240']


Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


{'0': {'precision': 0.9705882352941176, 'recall': 0.7983870967741935, 'f1-score': 0.8761061946902654, 'support': 248}, '1': {'precision': 0.40476190476190477, 'recall': 0.85, 'f1-score': 0.5483870967741935, 'support': 40}, 'accuracy': 0.8055555555555556, 'macro avg': {'precision': 0.6876750700280112, 'recall': 0.8241935483870968, 'f1-score': 0.7122466457322294, 'support': 288}, 'weighted avg': {'precision': 0.8920012449424214, 'recall': 0.8055555555555556, 'f1-score': 0.8305896533130332, 'support': 288}}


Aquí acaba el código de colab. Falta hacer el zip para poder descargar los resultados (y opcionalmente usar el bot para que me avise del final de la ejecución)

In [29]:
import requests

# Definir la URL base y los parámetros
url = "https://api.callmebot.com/whatsapp.php"
params = {
    "phone": "+34653508040",
    "apikey": "1512070",
    "text": "🤖¡Ejecución terminada! 🤖\nVe a echarle un vistazo ☝🤓"
}

# Enviar la solicitud GET
response = requests.get(url, params=params)

# Imprimir el estado de la respuesta
print(response.status_code)
print(response.text)

200
<p>Message to: +34653508040<p>Text to send: 🤖¡Ejecución terminada! 🤖%0AVe a echarle un vistazo ☝🤓<p><b>Message queued.</b> You will receive it in a few seconds.


In [31]:
!zip -r results_docs_bert.zip results_docs_bert
from IPython.display import FileLink 
FileLink(r'results_docs_bert.zip')

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


updating: results_docs_deberta/ (stored 0%)
updating: results_docs_deberta/res_docs_deberta_8.txt (deflated 57%)
updating: results_docs_deberta/res_docs_deberta_7.txt (deflated 57%)
updating: results_docs_deberta/res_docs_deberta_9.txt (deflated 58%)
updating: results_docs_deberta/res_docs_deberta_3.txt (deflated 67%)
updating: results_docs_deberta/res_docs_deberta_2.txt (deflated 56%)
updating: results_docs_deberta/res_docs_deberta_1.txt (deflated 57%)
updating: results_docs_deberta/res_docs_deberta_5.txt (deflated 58%)
updating: results_docs_deberta/res_docs_deberta_0.txt (deflated 57%)
updating: results_docs_deberta/res_docs_deberta_6.txt (deflated 57%)
updating: results_docs_deberta/res_docs_deberta_4.txt (deflated 58%)


/kaggle/working/results_docs_deberta.zip